os: linux
dist: bionic
services: docker
language: bash

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
install:
  - git clone https://github.com/elasyaf/nginx-fpm72.git  
  - docker build --no-cache -t 0xelasyaf/nginx-fpm72:latest .

script:
  - docker-compose up -d

after_script:
- docker ps
- docker images


