os: linux
dist: bionic
services: docker
language: bash

before_install:
  - git clone https://github.com/elasyaf/nginx-fpm72.git
  
install:  
  - docker build --no-cache -t 0xelasyaf/nginx-fpm72:latest .

script:
  - docker run -d -p 80:80 0xelasyaf/nginx-fpm72:latest /bin/bash -c "service nginx status && service php7.2-fpm status"
  - docker ps -a

after_script:
- docker images

