os:
  - ubuntu

services:
  - docker

before_install:
  - docker build --no-cache -t 0xelasyaf/nginx-fpm72:latest .
  - docker run -d -p 80:80 0xelasyaf/nginx-fpm72:latest /bin/bash -c "service nginx status && service php7.2-fpm status"
  - docker ps -a
  - docker run 0xelasyaf/nginx-fpm72:latest /bin/bash -c "service nginx status && service php7.2-fpm status"

script:
  - bundle exec rake test

