os: linux
dist: bionic
services: docker
language: bash

before_install:
  - git clone https://github.com/elasyaf/nginx-fpm72.git
  
install:  
  - docker build --no-cache -t 0xelasyaf/nginx-fpm72:latest .

script:
  - docker-compose up -d

after_script:
- docker images

