###### install nginx #####

- name: add PPA repository for Nginx
  apt_repository:
    repo: 'ppa:nginx/stable'

- name: install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

###### Copy conf.d #####


- name: copy fastcgi-fpm
  template:
      src: templates/conf.d/fastcgi-fpm.conf.j2
      dest: /etc/nginx/conf.d/fastcgi-fpm.conf


###### Copy nginx.conf #####

- name: copy magento configuration
  template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

###### sites-available #####

- name: copy magento configuration
  template:
      src: templates/sites-available/default.j2
      dest: /etc/nginx/sites-available/default