---
- name: add PPA repository for PHP 7.2
  apt_repository:
        repo: 'ppa:ondrej/php'

- name: install PHP 7.2 component
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - php7.2-fpm
    - php7.2-cli
    - php7.2-common
    - php7.2-gd
    - php7.2-mysql
    #- php7.2-mcrypt
    - php7.2-curl
    - php7.2-intl
    - php7.2-xsl
    - php7.2-mbstring
    - php7.2-zip
    - php7.2-bcmath
    - php7.2-iconv
    - php7.2-imap
    - php7.2-xmlrpc
    - php7.2-dev
    - php7.2-soap